source 'https://rubygems.org'

gem 'rails', '4.1.0'

gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'pg'
gem 'mustache-js-rails'
gem 'gistyle'
gem 'gon'
gem 'color-generator'
gem 'ledermann-rails-settings'
gem 'rest_in_place', github: 'benphelps/rest_in_place'
gem 'jbuilder', '~> 1.2'
gem 'sprockets-rails'
gem 'kramdown'
gem 'devise'
gem 'haml-rails'
gem 'friendly_id', '~> 5.0.0'
gem 'yajl-ruby'
gem 'faye-redis'
gem 'danthes', '1.0.4'
gem 'thin'
gem 'better_errors'
gem 'binding_of_caller'
gem 'rails_config'
gem 'bootsy', github: 'volmer/bootsy'
gem 'fog'
gem 'carrierwave', github: 'carrierwaveuploader/carrierwave'
gem 'mini_magick', '~> 3.7.0'
gem 'nokogiri'
gem 'multi_xml'
gem 'non-stupid-digest-assets'
gem 'rails_emoji', '~> 1.7.1'
gem 'httparty'
gem 'dalli'
gem 'vacuum'
gem 'musicbrainz'
gem 'asset_sync'

gem 'capistrano', '~> 3.0', require: false, group: :development
gem 'capistrano-rvm'
gem 'capistrano-rails',   '~> 1.1'
gem 'capistrano-bundler', '~> 1.1'

group :development do
  gem 'sqlite3'
  gem 'awesome_print'
  gem 'rack-mini-profiler'
end