development:
  server: "http://watchme.dev/sock"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "https://watchme.io/sock/faye"
  secret_token: "secret"
  signature_expiration: 3600
